### ISSUE TITLE
After log in packet 0x06 is called

### ISSUE THREAD

**Issue by fabiohvp** [UltimaPHP/UltimaPHP#58]
This packet triggers dclick and if the player is mounted he will unmount.

**Comment by gokaygurcan** [comment]
Hi,

I don't think this is necessarily a bug. As far as I can see (and understand) from RunUO/ServUO & Razor packet logs, it's totally normal for client to send 0x06 after login. Seems like it tries to open paperdoll when you first log in. Sometimes, razor blocks this request and sends it afterwards but still it's not a bug imho. 

```
12:50:15.0796: Client -> Server [BLOCKED] 0x06 (Length: 5)
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   06 40 00 08 49                                     .@..I


12:50:15.0805: Razor -> Server 0x06 (Length: 5)
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   06 40 00 08 49                                     .@..I
```

**Comment by joaoescribano** [comment]
@gokaygurcan exactly, this is a normal action that's been forced by the client as far I can tell too:
![image](https://user-images.githubusercontent.com/1336613/68171355-28e4df80-ff52-11e9-839d-0787c07c012e.png)

It's also already threated by UltimaPHP: https://github.com/UltimaPHP/UltimaPHP/blob/master/core/player.class.php#L256
