### ISSUE TITLE
UOtiledata.mul failed

### ISSUE THREAD

**Issue by ghost** [UltimaPHP/UltimaPHP#64]
client version ; 7.0.72.0
When starting the server, i'm stuck on this error:
12:46:28 (DANGER) : Loading file C:/UOtiledata.mul failed!

i'm using windows 10 x64  
Any ideas ?

**Comment by fabiohvp** [comment]
Did you set the path at ultimaphp.ini? You must point it to your UO folder

**Comment by mbnunes** [comment]
In ultimaphp.ini in UO path. Terminate Path with / example:

C:/UO/

**Comment by ghost** [comment]
Thanks , it was the  "/" after C:/UO missing.
